[package]
name = "hubbard-trexio"
version = "0.1.0"
edition = "2024"
description = "Generates TREXIO files containing one- and two-electron integrals for the Hubbard model"
license = "GPL-3.0-or-later"

[[bin]]
name = "hubbard-trexio"
path = "src/main.rs"

[dependencies]
ndarray = "0.17.2"
trexio = "2.5.1"
